name: Run Playwright in Docker (spec only)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t playwright-tests .

      - name: Run Playwright tests in Docker
        run: docker run --platform linux/amd64 --rm playwright-tests